const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
const PDFDocument = require('pdfkit');
const path = require('path');

const s3 = new S3Client({
  region: process.env.AWS_REGION || 'us-west-1',
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID || '',
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || '',
  }
});

const formatCA_Date = (date) => {
  if (!date) return '—';
  return new Intl.DateTimeFormat('en-GB', {
    timeZone: 'America/Los_Angeles',
    day: '2-digit',
    month: '2-digit',
    year: 'numeric'
  }).format(new Date(date));
};

const formatCA_DateTime = (date) => {
  if (!date) return '—';
  return new Intl.DateTimeFormat('en-GB', {
    timeZone: 'America/Los_Angeles',
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: true
  }).format(new Date(date));
};

const generateInvoicePDFBuffer = (order, shop) => {
  return new Promise((resolve, reject) => {
    // US Letter page size is 612 x 792 points
    const PAGE_WIDTH = 612;
    const PAGE_HEIGHT = 792;
    const MARGIN_LEFT = 50;
    const MARGIN_RIGHT = 50;
    const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT; // 512
    const PAGE_BOTTOM = PAGE_HEIGHT - 30; // bottom margin (762pt)
    // Maximum Y for product table rows — small margin so rows don't touch the absolute page edge
    const MAX_TABLE_Y = PAGE_BOTTOM - 20; // 742pt

    const doc = new PDFDocument({ margins: { top: 40, bottom: 30, left: 50, right: 50 }, size: 'LETTER', autoFirstPage: true });
    const buffers = [];
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => {
      resolve(Buffer.concat(buffers));
    });
    doc.on('error', reject);

    const logoPath = path.join(__dirname, '../uploads/logo.png');

    // ── Helper: Draw watermark on the current page ──
    const drawWatermark = () => {
      doc.save();
      doc.opacity(0.08);
      doc.image(logoPath, 106, 196, { width: 400 });
      doc.restore();
    };

    // ── Helper: Draw table header row ──
    const drawTableHeader = (y) => {
      doc.rect(MARGIN_LEFT, y, CONTENT_WIDTH, 22).fill('#002d72');
      doc.fillColor('#ffffff').fontSize(9).font('Helvetica-Bold');
      doc.text('S.No.', 55, y + 7, { width: 30 });
      doc.text('Product Name', 88, y + 7, { width: 180 });
      doc.text('SKU ID', 270, y + 7, { width: 70 });
      doc.text('Qty', 340, y + 7, { width: 40, align: 'right' });
      doc.text('Unit Price', 390, y + 7, { width: 80, align: 'right' });
      doc.text('Total', 480, y + 7, { width: 72, align: 'right' });
      return y + 22;
    };

    // ── Helper: Add a continuation page with accent stripe, watermark, and table header ──
    const addContinuationPage = () => {
      doc.addPage();
      // Top accent stripe
      doc.rect(0, 0, PAGE_WIDTH, 10).fill('#002d72');
      // Watermark
      drawWatermark();
      // Table header starts below the accent stripe with some padding
      const headerY = 30;
      return drawTableHeader(headerY);
    };

    // ── Helper: Draw footer on current page ──
    const drawFooter = (footerTop) => {
      doc.strokeColor('#e2e8f0').lineWidth(1).moveTo(MARGIN_LEFT, footerTop).lineTo(562, footerTop).stroke();

      let permitText = `Customer Seller Permit: ${shop.seller_permit || 'N/A'}`;
      if (shop.tobacco_license) {
        permitText += `  |  Customer Tobacco License: ${shop.tobacco_license}`;
      }
      doc.fillColor('#475569').fontSize(8).font('Helvetica-Bold').text(permitText, MARGIN_LEFT, footerTop + 8, { align: 'center', width: CONTENT_WIDTH });

      doc.fillColor('#94a3b8').fontSize(8).font('Helvetica').text('Thank you for your business', MARGIN_LEFT, footerTop + 20, { align: 'center', width: CONTENT_WIDTH });

      const genTime = formatCA_DateTime(new Date());
      doc.fillColor('#cbd5e1').text(`Generated by Woodland Distributors on ${genTime}`, MARGIN_LEFT, footerTop + 32, { align: 'center', width: CONTENT_WIDTH });
    };

    // ═══════════════════════════════════════════════════
    // PAGE 1: Header, Bill To, Watermark, Table Start
    // ═══════════════════════════════════════════════════

    // 2. Top Accent Stripe
    doc.rect(0, 0, PAGE_WIDTH, 10).fill('#002d72');

    // 3. Header Branding
    doc.fillColor('#002d72').fontSize(22).font('Helvetica-Bold').text('Woodland Distributors', 50, 32);

    // 4. Invoice Title & Metadata (Right Aligned)
    doc.fillColor('#1e293b').fontSize(22).font('Helvetica-Bold').text('INVOICE', 400, 35, { align: 'right', width: 162 });
    
    // Invoice Metadata Table on the Right
    const metaY = 75;
    doc.fontSize(9).font('Helvetica');
    doc.fillColor('#64748b').text('Invoice No:', 400, metaY, { width: 70, align: 'left' });
    doc.fillColor('#1e293b').font('Helvetica-Bold').text(`INV-${order.id}`, 470, metaY, { width: 92, align: 'right' });
    
    doc.fillColor('#64748b').font('Helvetica').text('Date:', 400, metaY + 14, { width: 70, align: 'left' });
    const dateVal = order.delivered_at ? new Date(order.delivered_at) : new Date(order.created_at || new Date());
    doc.fillColor('#1e293b').text(formatCA_Date(dateVal), 470, metaY + 14, { width: 92, align: 'right' });
    
    doc.fillColor('#64748b').text('Order ID:', 400, metaY + 28, { width: 70, align: 'left' });
    doc.fillColor('#1e293b').text(`WS-${order.id}`, 470, metaY + 28, { width: 92, align: 'right' });

    // 5. Company Address (Left Aligned below tagline)
    doc.font('Helvetica').fillColor('#475569');
    doc.text('1233 E Beamer St Suite E1', 50, 90);
    doc.text('Woodland, CA 95776, United States', 50, 102);
    doc.text('Phone: +1 530-490-8786', 50, 114);

    // Divider
    doc.strokeColor('#e2e8f0').lineWidth(1).moveTo(50, 155).lineTo(562, 155).stroke();

    // 6. Bill To Information
    const billToY = 170;
    doc.fillColor('#002d72').fontSize(10).font('Helvetica-Bold').text('BILL TO', 50, billToY);
    doc.fillColor('#0f172a').fontSize(11).font('Helvetica-Bold').text(shop.shop_name, 50, billToY + 15);
    doc.font('Helvetica').fontSize(9).fillColor('#334155');
    doc.text(`Contact: ${shop.owner_name}`, 50, billToY + 30);
    doc.text(`Phone: ${shop.contact_details || 'N/A'}`, 50, billToY + 42);
    doc.text(`Address: ${[shop.address, shop.city, shop.state, shop.zip].filter(Boolean).join(', ') || 'N/A'}`, 50, billToY + 54, { width: 350 });
    doc.text(`Seller Permit: ${shop.seller_permit || 'N/A'}`, 50, billToY + 66);
    if (shop.tobacco_license) {
      doc.text(`Tobacco License: ${shop.tobacco_license}`, 50, billToY + 78);
    }

    // 6a. Watermark (drawn behind content on page 1)
    drawWatermark();

    // 7. Itemized Product Table
    const tableTop = 295;
    let position = drawTableHeader(tableTop);
    
    doc.fontSize(9).font('Helvetica');
    


    (order.OrderItems || []).forEach((item, index) => {
      const name = item.Product?.billing_name || item.Product?.name || `Product #${item.product_id}`;
      const skuId = item.Product?.sku_id || '—';
      const reqQty = item.requested_qty;
      const appQty = item.approved_qty ?? reqQty;
      const finalPrice = (item.custom_price !== null && item.custom_price !== undefined) ? item.custom_price : item.price;
      const total = finalPrice * appQty;
      
      // Calculate dynamic row height based on wrapped name string height
      doc.fontSize(9).font('Helvetica');
      const textHeight = doc.heightOfString(name, { width: 180 });
      const rowHeight = Math.max(22, textHeight + 10);
      
      // ── Page break check ──
      // Check if this row fits on the current page. If not, start a new page.
      if (position + rowHeight > MAX_TABLE_Y) {
        position = addContinuationPage();
        doc.fontSize(9).font('Helvetica');
      }
      
      // Table columns are transparent to allow watermark to show through
      
      // Text drawing
      doc.fillColor('#1e293b');
      const serialNo = index + 1;
      doc.text(String(serialNo), 55, position + (rowHeight - 9) / 2, { width: 30 });
      doc.text(name, 88, position + (rowHeight - textHeight) / 2, { width: 180 });
      
      const valOffset = position + (rowHeight - 9) / 2;
      doc.text(skuId, 270, valOffset, { width: 70 });
      doc.text(String(appQty), 340, valOffset, { width: 40, align: 'right' });
      doc.text(`$${finalPrice.toFixed(2)}`, 390, valOffset, { width: 80, align: 'right' });
      doc.text(`$${total.toFixed(2)}`, 480, valOffset, { width: 72, align: 'right' });
      
      // Underline border
      doc.strokeColor('#f1f5f9').lineWidth(0.5).moveTo(50, position + rowHeight).lineTo(562, position + rowHeight).stroke();
      
      position += rowHeight;
    });

    // 8. Totals Section
    // Accurately check if totals + footer fit on the current page.
    // Totals section uses 73pt (15+10+15+8+25). Footer placed at max(posAfterTotals+10, 720)
    // and occupies ~42pt. Only create a new page if they genuinely don't fit.
    const posAfterTotals = position + 73;
    const estFooterTop = Math.max(posAfterTotals + 10, 720);
    if (estFooterTop + 42 > PAGE_BOTTOM) {
      doc.addPage();
      doc.rect(0, 0, PAGE_WIDTH, 10).fill('#002d72');
      drawWatermark();
      position = 30;
    }

    position += 15;
    doc.strokeColor('#e2e8f0').lineWidth(1).moveTo(350, position).lineTo(562, position).stroke();
    position += 10;
    
    // Calculate totals
    let finalSubtotal = 0;
    (order.OrderItems || []).forEach(item => {
      const appQty = item.approved_qty ?? item.requested_qty;
      const finalPrice = (item.custom_price !== null && item.custom_price !== undefined) ? item.custom_price : item.price;
      finalSubtotal += finalPrice * appQty;
    });

    // Subtotal
    doc.fillColor('#64748b').fontSize(9).font('Helvetica');
    doc.text('Subtotal:', 350, position, { width: 100, align: 'right' });
    doc.fillColor('#1e293b').font('Helvetica-Bold').text(`$${finalSubtotal.toFixed(2)}`, 450, position, { width: 112, align: 'right' });
    position += 15;

    // Line above Grand Total
    doc.strokeColor('#cbd5e1').lineWidth(0.5).moveTo(350, position).lineTo(562, position).stroke();
    position += 8;

    // Grand Total
    doc.fillColor('#475569').fontSize(10).font('Helvetica-Bold');
    doc.text('Final Payable:', 350, position, { width: 100, align: 'right' });
    doc.fillColor('#002d72').fontSize(14).font('Helvetica-Bold');
    doc.text(`$${finalSubtotal.toFixed(2)}`, 450, position - 3, { width: 112, align: 'right' });

    position += 25;

    // 9. Footer (positioned dynamically on the last page)
    // Place footer at the bottom of the page, or just below totals if totals are low enough
    const footerTop = Math.max(position + 10, 720);
    drawFooter(footerTop);

    doc.end();
  });
};

const uploadInvoicePDF = async (order, shop) => {
  const buffer = await generateInvoicePDFBuffer(order, shop);
  const key = `invoices/invoice-${order.id}-${Date.now()}.pdf`;
  const bucket = process.env.AWS_S3_BUCKET || 'wdistro';
  
  await s3.send(new PutObjectCommand({
    Bucket: bucket,
    Key: key,
    Body: buffer,
    ContentType: 'application/pdf',
  }));

  return `https://${bucket}.s3.${process.env.AWS_REGION || 'us-west-1'}.amazonaws.com/${key}`;
};

module.exports = {
  uploadInvoicePDF,
};
